### ISSUE TITLE
Issue with LayoutRotateCell

### ISSUE THREAD

**Issue by victorpreuss** [wulffern/ciccreator#47]
Hi Carsten,

As I was playing around with ciccreator and running some tests, I kept getting segmentation faults when using the examples/routes.json.

The code crashes at the **TEST_R** and **TEST_MY** cells due to the _LayoutRotateCell_ property. When I remove the field `"class" : "Layout::LayoutRotateCell"` it works all the way to the end, but there is no rotation to the resulting layout despite the `"rotateAngle" : "R90"` property.

I've tested with the master branch version and release 0.1.5 with same results. I'm compiling the software by running make on a Debian machine

Also, in the examples I have not seen any vias being generated, even on the SAR example. Is there a particular version of the tool for which the examples where created?

Thank you!

**Comment by wulffern** [comment]
Hi. Thanks for letting me know about the problem. Seems like I had a wrong type on a function, or the handling of QJsonValue has changed in QT 6. Hopefully it works now.

**Comment by wulffern** [comment]
I've also fixed the handling of the cuts (vias) in the cic-gui. You should see them now. BTW: To turn the .cic into other formats, have a look at the cicpy on my github

**Comment by victorpreuss** [comment]
Quickly tested and both issues seem to have disappeared (crash and vias missing). Thanks!
